// 03-Frontend-Development/04-Events-Forms-and-Lists/src/TodoApp.jsx
import { useState } from 'react'

let nextId = 1

// Demonstrates: a CONTROLLED input (its value lives in React state, not the DOM --
// `value={text}` + `onChange` is what makes it controlled, versus an uncontrolled
// input that manages its own value and is read only on demand via a ref),
// preventDefault() to stop a form's default full-page-reload submit behavior,
// and immutable list updates (.map()/.filter() returning NEW arrays, never
// mutating `todos` in place -- React compares the old and new array references
// to decide whether to re-render, so mutating in place would make it think
// nothing changed).
export function TodoApp() {
  const [todos, setTodos] = useState([])
  const [text, setText] = useState('')

  function handleSubmit(event) {
    event.preventDefault()
    const trimmed = text.trim()
    if (trimmed === '') return // reject empty/whitespace-only submissions

    setTodos((prev) => [...prev, { id: nextId++, text: trimmed, done: false }])
    setText('') // clear the controlled input after a successful add
  }

  function toggleTodo(id) {
    setTodos((prev) =>
      prev.map((todo) => (todo.id === id ? { ...todo, done: !todo.done } : todo)),
    )
  }

  function deleteTodo(id) {
    setTodos((prev) => prev.filter((todo) => todo.id !== id))
  }

  return (
    <div>
      <form onSubmit={handleSubmit}>
        <label htmlFor="todo-input">New task</label>
        <input
          id="todo-input"
          value={text}
          onChange={(event) => setText(event.target.value)}
        />
        <button type="submit">Add</button>
      </form>

      {todos.length === 0 ? (
        <p role="status">No tasks yet.</p>
      ) : (
        <ul>
          {todos.map((todo) => (
            <li key={todo.id}>
              <label>
                <input
                  type="checkbox"
                  checked={todo.done}
                  onChange={() => toggleTodo(todo.id)}
                />
                <span style={{ textDecoration: todo.done ? 'line-through' : 'none' }}>
                  {todo.text}
                </span>
              </label>
              <button onClick={() => deleteTodo(todo.id)} aria-label={`Delete ${todo.text}`}>
                Delete
              </button>
            </li>
          ))}
        </ul>
      )}
    </div>
  )
}

// 03-Frontend-Development/09-Other-Frameworks/src/TodoApp.vue
<script setup>
// The deliberate point of this file: it's the SAME app as Lesson 04's
// TodoApp.jsx (add/toggle/delete, reject blank input, empty-state message),
// rewritten in Vue's Composition API, specifically so the two can be read
// side-by-side to see what actually differs.
import { ref } from 'vue'

let nextId = 1
const todos = ref([])
const text = ref('')

function addTodo() {
  const trimmed = text.value.trim()
  if (trimmed === '') return
  todos.value.push({ id: nextId++, text: trimmed, done: false })
  text.value = ''
}

function toggleTodo(id) {
  const todo = todos.value.find((t) => t.id === id)
  if (todo) todo.done = !todo.done
}

function deleteTodo(id) {
  todos.value = todos.value.filter((t) => t.id !== id)
}
</script>

<template>
  <div>
    <form @submit.prevent="addTodo">
      <label for="todo-input">New task</label>
      <input id="todo-input" v-model="text" />
      <button type="submit">Add</button>
    </form>

    <p v-if="todos.length === 0" role="status">No tasks yet.</p>
    <ul v-else>
      <li v-for="todo in todos" :key="todo.id">
        <label>
          <input type="checkbox" :checked="todo.done" @change="toggleTodo(todo.id)" />
          <span :style="{ textDecoration: todo.done ? 'line-through' : 'none' }">
            {{ todo.text }}
          </span>
        </label>
        <button @click="deleteTodo(todo.id)" :aria-label="`Delete ${todo.text}`">Delete</button>
      </li>
    </ul>
  </div>
</template>
